apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: rolearn: arn:aws:iam::007740003734:role/hr-dev-eks-nodegroup-role
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
  mapUsers: |
    - userarn: arn:aws:iam::007740003734:user/eksadmin1
      username:  eksadmin1
      groups:
        - system:masters
    - userarn: arn:aws:iam::007740003734:user/eksadmin2
      username: eksadmin2
      groups:
         - system:master